# Generated by Django 6.0.1 on 2026-01-27 20:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen', models.CharField(help_text='Test specimen identifier', max_length=255)),
                ('binder_grade', models.CharField(help_text='Binder grade specification', max_length=100)),
                ('file_type', models.CharField(help_text='Type of input file (enum placeholder)', max_length=50)),
                ('allowed_rut_depth', models.FloatField(help_text='Maximum allowed rut depth in mm', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the test run', null=True)),
                ('file_path', models.CharField(help_text='Path to the test data file', max_length=500)),
                ('status', models.CharField(help_text='Test run status (enum placeholder)', max_length=50)),
                ('errors', models.TextField(blank=True, help_text='Error messages if any', null=True)),
                ('analysis_version', models.IntegerField(help_text='Version of the analysis algorithm used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passes_total', models.BigIntegerField(help_text='Total number of passes in the test', validators=[django.core.validators.MinValueValidator(0)])),
                ('rut_depth_5000', models.FloatField(help_text='Rut depth at 5000 passes (mm)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rut_depth_10000', models.FloatField(help_text='Rut depth at 10000 passes (mm)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rut_depth_15000', models.FloatField(help_text='Rut depth at 15000 passes (mm)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rut_depth_20000', models.FloatField(help_text='Rut depth at 20000 passes (mm)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rut_depth_final', models.FloatField(blank=True, help_text='Final rut depth measurement (mm)', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('passes_to_failure', models.FloatField(blank=True, help_text='Number of passes until failure occurred', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('inflection_pass', models.BigIntegerField(blank=True, help_text='Pass number where inflection point occurred', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('test_duration', models.DurationField(help_text='Total duration of the test')),
                ('rating', models.FloatField(help_text='Numerical rating of the test results')),
                ('rating_classification', models.CharField(help_text='Classification of the rating (enum placeholder)', max_length=50)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.testrun')),
            ],
            options={
                'verbose_name_plural': 'Test Results',
                'db_table': 'test_results',
            },
        ),
        migrations.CreateModel(
            name='TestMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_count', models.IntegerField(help_text='Pass number for this measurement', validators=[django.core.validators.MinValueValidator(0)])),
                ('rut_depth_mm', models.FloatField(help_text='Measured rut depth in millimeters', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ref_depth_mm', models.FloatField(blank=True, help_text='Reference depth measurement in millimeters', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.testrun')),
            ],
            options={
                'verbose_name_plural': 'Test Measurements',
                'db_table': 'test_measurements',
                'ordering': ['pass_count'],
            },
        ),
        migrations.CreateModel(
            name='TestArtifacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Type of artifact (enum placeholder: IMAGE, VIDEO, REPORT, LOG, etc.)', max_length=50)),
                ('path', models.CharField(help_text='File path or URL to the artifact', max_length=500)),
                ('test_results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.testresults')),
            ],
            options={
                'verbose_name_plural': 'Test Artifacts',
                'db_table': 'test_artifacts',
                'indexes': [models.Index(fields=['test_results', 'type'], name='test_artifa_test_re_f11881_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['user', 'status'], name='test_run_user_id_fb5c36_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['created_at'], name='test_run_created_b31a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['status'], name='test_run_status_b89e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='testresults',
            index=models.Index(fields=['test_run'], name='test_result_test_ru_14e083_idx'),
        ),
        migrations.AddIndex(
            model_name='testresults',
            index=models.Index(fields=['rating_classification'], name='test_result_rating__ee9f16_idx'),
        ),
        migrations.AddIndex(
            model_name='testmeasurements',
            index=models.Index(fields=['test_run', 'pass_count'], name='test_measur_test_ru_47c74d_idx'),
        ),
    ]
