# Generated by Django 6.0.1 on 2026-02-09 21:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='file_path',
        ),
        migrations.AddField(
            model_name='testrun',
            name='file',
            field=models.FileField(default='', help_text='data file', upload_to='uploads/%Y/%m/%d/', validators=[core.models.validate_file]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresults',
            name='rating_classification',
            field=models.CharField(choices=[(1, 'EXCELLENT'), (2, 'GOOD'), (3, 'FAIR'), (4, 'POOR')], help_text='Classification of the rating (enum placeholder)'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED')], help_text='Test run status'),
        ),
    ]
