# Generated by Django 6.0.1 on 2026-02-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_testrun_file_path_testrun_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='passes_vs_rut',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
