# Generated by Django 6.0.1 on 2026-02-19 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testresults_passes_vs_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='passes_total',
            field=models.BigIntegerField(help_text='Total number of passes in the test', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='rating',
            field=models.FloatField(help_text='Numerical rating of the test results', null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='rating_classification',
            field=models.CharField(choices=[(1, 'EXCELLENT'), (2, 'GOOD'), (3, 'FAIR'), (4, 'POOR')], help_text='Classification of the rating (enum placeholder)', null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='rut_depth_10000',
            field=models.FloatField(help_text='Rut depth at 10000 passes (mm)', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='rut_depth_15000',
            field=models.FloatField(help_text='Rut depth at 15000 passes (mm)', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='rut_depth_20000',
            field=models.FloatField(help_text='Rut depth at 20000 passes (mm)', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='rut_depth_5000',
            field=models.FloatField(help_text='Rut depth at 5000 passes (mm)', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='test_duration',
            field=models.DurationField(help_text='Total duration of the test', null=True),
        ),
    ]
