# Generated by Django 6.0.1 on 2026-02-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_testresults_passes_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='passes_vs_rut',
            field=models.TextField(),
        ),
    ]
