# Generated by Django 6.0.1 on 2026-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_testrun_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'INSTRATEK'), (2, 'TROXLER'), (3, 'PTI'), (4, 'CUSTOM')], help_text='Type of input file (enum placeholder)'),
        ),
    ]
