# Generated by Django 6.0.1 on 2026-02-20 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_testrun_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinderGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testrun',
            name='binder_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bindergrade'),
        ),
    ]
