# Generated by Django 6.0.1 on 2026-02-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bindergrade_alter_testrun_binder_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindergrade',
            name='max_rut',
            field=models.FloatField(null=True),
        ),
    ]
