# Generated by Django 6.0.1 on 2026-02-20 23:32

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bindergrade_max_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindergrade',
            name='max_rut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testartifacts',
            name='type',
            field=models.CharField(help_text='Type of artifact (IMAGE, VIDEO, REPORT, LOG, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='rating_classification',
            field=models.IntegerField(blank=True, choices=[(1, 'EXCELLENT'), (2, 'GOOD'), (3, 'FAIR'), (4, 'POOR')], help_text='Classification of the rating', null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='test_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.testrun'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='file',
            field=models.FileField(help_text='Data file', upload_to='uploads/%Y/%m/%d/', validators=[core.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'INSTRATEK'), (2, 'TROXLER'), (3, 'PTI'), (4, 'CUSTOM')], help_text='Type of input file'),
        ),
    ]
