# Generated by Django 6.0.1 on 2026-02-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_bindergrade_max_rut_alter_testartifacts_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindergrade',
            name='passes_to_rut',
            field=models.PositiveIntegerField(blank=True, help_text='Default number of passes to rut failure', null=True),
        ),
        migrations.AlterField(
            model_name='bindergrade',
            name='max_rut',
            field=models.FloatField(blank=True, help_text='Default maximum rut depth (mm)', null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'INSTROTEK'), (2, 'TROXLER'), (3, 'PTI'), (4, 'CUSTOM')], help_text='Type of input file'),
        ),
    ]
