# Generated by Django 6.0.1 on 2026-03-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bindergrade_passes_to_rut_alter_bindergrade_max_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='passes_vs_rut_denoise',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
